;;; 包安装与配置分离，利于包版本集中管理，利于灵活调整包管理工具
(straight-use-package 'company)
(straight-use-package '(emacs-application-framework :host github :repo "manateelazycat/emacs-application-framework" :files ("app" "core" "*.el" "*.py")))
(straight-use-package 'counsel)
(straight-use-package 'expand-region)
(straight-use-package '(fuz :host github :repo "rustify-emacs/fuz.el" :files ("src" "Cargo*" "*.el")))
(straight-use-package 'gcmh)
(straight-use-package 'ivy)
(straight-use-package 'ivy-posframe)
(straight-use-package 'magit)
(straight-use-package 'markdown-mode)
(straight-use-package '(nox :host github :repo "manateelazycat/nox"))
(straight-use-package 'org)
(straight-use-package '(paredit :repo "http://mumble.net/~campbell/git/paredit.git/"))
(straight-use-package 'posframe)
(straight-use-package '(rime :host github :repo "DogLooksGood/emacs-rime" :files ("*.el" "Makefile" "lib.c")))
;(straight-use-package 'smex)
(straight-use-package '(snails :host github :repo "manateelazycat/snails" :files ("*.el" "*.sh" "*.ps1") :no-byte-compile t))
(straight-use-package 'typescript-mode)
(straight-use-package 'which-key)
(straight-use-package 'yasnippet)

(provide 'init-packages)
