(straight-use-package 'diminish)

(with-eval-after-load 'hi-lock (diminish 'hi-lock-mode "亮"))
(with-eval-after-load 'simple (diminish 'visual-line-mode "⮒"))
(with-eval-after-load 'view (diminish 'view-mode "览"))
(with-eval-after-load 'winner (diminish 'winner-mode))
(with-eval-after-load 'abbrev (diminish 'abbrev-mode "缩"))
(with-eval-after-load 'magit-delta (diminish 'magit-delta-mode))
(with-eval-after-load 'eldoc (diminish 'eldoc-mode "档"))
(with-eval-after-load 'hideshow (diminish 'hs-minor-mode "折"))
(with-eval-after-load 'lispy (diminish 'lispy-mode))
(with-eval-after-load 'yasnippet (diminish 'yas-minor-mode "模"))
(with-eval-after-load 'flycheck (diminish 'flycheck-mode "检"))
(with-eval-after-load 'flyspell (diminish 'flyspell-mode))
(with-eval-after-load 'gcmh (diminish 'gcmh-mode))
(with-eval-after-load 'selectric-mode (diminish 'selectric-mode))
(with-eval-after-load 'page-break-lines (diminish 'page-break-lines-mode))
(with-eval-after-load 'company (diminish 'company-mode "补"))
(with-eval-after-load 'isearch (diminish 'isearch-mode))
(with-eval-after-load 'subword (diminish 'subword-mode))

(provide 'w-diminish)
